### ISSUE TITLE
Blazor Wasm - ValidationProblemDetails in Microsoft.AspNetCore.Mvc

### ISSUE THREAD

**Issue by carlblanchard** [dotnet/linker#1251]
Hi, I'm developing a Blazor client application and have references to Microsoft.AspNetCore.Mvc; in order to use the  ValidationProblemDetails to discover what validation failed on my web service. 
Everything has been working locally just fine. My DevOps build now fails with 
```
Fatal error in Mono IL Linker
##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): Error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions::AddAuthorizationServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)' in assembly: 'Microsoft.AspNetCore.Mvc.Core.dll'
C:\Users\VssAdministrator\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions::AddAuthorizationServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)' in assembly: 'Microsoft.AspNetCore.Mvc.Core.dll' [D:\a\1\s\MySoftware.ProductName.AppName\MySoftware.ProductName.AppName.csproj]
   ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions::AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection)
     at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): Error : ILLink failed with exit code -532462766.
C:\Users\VssAdministrator\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): error : ILLink failed with exit code -532462766. [D:\a\1\s\MySoftware.ProductName.AppName\MySoftware.ProductName.AppName.csproj]
Done Building Project "D:\a\1\s\MySoftware.ProductName.AppName\MySoftware.ProductName.AppName.csproj" (default targets) -- FAILED.
Project "D:\a\1\s\MySoftware.ProductName.AppName.sln" (1) is building "D:\a\1\s\AppName.Tests\AppName.Tests.csproj" (3) on node 1 (default targets).
UpdateFeatureFilesInProject:
```

**Comment by vitek-karas** [comment]
Very sorry for never responding to this issue.

The failure on its own will be hard to diagnose. My guess would be that there's some version mismatch somewhere and that some part of the app depends on a method which has been removed in newer version of the assembly.
The method in question: ` Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions::AddAuthorization`

Since it's been so long, I'm going to close this issue. If you're still having problems like this, feel free to reopen the issue, or open a new one.
