### ISSUE TITLE
Error IL1012: IL Linker has encountered an unexpected error.

### ISSUE THREAD

**Issue by rpcob** [dotnet/linker#1849]
ILLink(0,0): Error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
Fatal error in IL Linker
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Mono.Cecil.MetadataReader.GetModuleFileName(String name)
   at Mono.Cecil.MetadataReader.ReadModules()
   at Mono.Cecil.AssemblyDefinition.<>c.<get_Modules>b__14_0(AssemblyDefinition _, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.AssemblyDefinition.get_Modules()
   at Mono.Linker.Steps.BlacklistStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)

**Comment by marek-safar** [comment]
This looks like Cecil bug or some obfuscated assembly. Could you attach the assembly?

**Comment by rpcob** [comment]
The assembly that breaks Linker is System.Web.Extensions.dll
<Reference Include="System.Web.Extensions">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Web.Extensions.dll</HintPath>
    </Reference>

**Comment by vitek-karas** [comment]
Sorry for such a late reply. Based on the callstack this could be some issue with file paths and how linker resolves assemblies. That said we haven't seen this elsewhere.

Can you please try with the latest SDK (.NET 6 Preview 5 or newer)?
Or maybe there's some repro you can share?

**Comment by vitek-karas** [comment]
Closing for inactivity. If the problem is still present, please reopen the issue.
