### ISSUE TITLE
error IL1012: IL Linker has encountered an unexpected error.

### ISSUE THREAD

**Issue by oliversalzburg** [dotnet/linker#2361]
I am investigating a CI build failure of a project that I am hardly familiar with. This project built just fine a couple of days ago and without any changes to the code base, is failing reliably today.

From what I can tell, this is the relevant part of the build log relating to the error:
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [C:\gitlab-runner\builds\qFSfUy_u\0\fairmanager-frontend\2081_fairmanager_eventplatform\Fairmanager.Admin\Fairmanager.Admin.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\WINDOWS\system32\config\systemprofile\.nuget\packages\microsoft.netcore.app.runtime.browser-wasm\5.0.12\runtimes\browser-wasm\lib\net5.0\System.Net.Primitives.dll'.
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
     at Mono.Linker.DirectoryAssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.ResolveFromReferences(AssemblyNameReference name, Collection`1 references, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name)
     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
     at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
     at Mono.Cecil.ExportedType.Resolve()
     at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(LinkContext context, AssemblyDefinition assembly, RootVisibility rootVisibility)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(AssemblyDefinition assembly)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Build continuing because "ContinueOnError" on the task "ILLink" is set to "ErrorAndContinue".
ILLink:
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\5.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [C:\gitlab-runner\builds\qFSfUy_u\0\fairmanager-frontend\2081_fairmanager_eventplatform\Fairmanager.Admin\Fairmanager.Admin.csproj]
Done Building Project "C:\gitlab-runner\builds\qFSfUy_u\0\fairmanager-frontend\2081_fairmanager_eventplatform\Fairmanager.Admin\Fairmanager.Admin.csproj" (Publish target(s)) -- FAILED.
```

**Comment by marek-safar** [comment]
This looks like some SDK is passing the wrong assembly path. Do you have any repro we could try to reproduce this? 

/cc @sbomer

**Comment by oliversalzburg** [comment]
The build of this project failed reliably. I could share an archive of the repo code privately if that helps. In that case, please let me know where to send it.

**Comment by vitek-karas** [comment]
What I find weird is that it seems the build is running under the SYSTEM account.
Anyway - I don't think that repro project alone would help here. What might be better is if you could get us the msbuild binlog (run the build with `-bl` command line option, this should produce `msbuild.binlog`). Note that such file will contain information about the machine and the current user (env. variables and such).

**Comment by oliversalzburg** [comment]
@vitek-karas I already sent a binlog to Sven Boemer earlier, after he told me he can't repro with the project source code alone.
The fact that it's using the SYSTEM account is probably because the account running the CI worker is a service account. This could probably be changed, but it hasn't been an issue for the past years we've been using this setup.

**Comment by vitek-karas** [comment]
@oliversalzburg thanks for the info... I'll discuss with @sbomer what the problem could be.

**Comment by vitek-karas** [comment]
As far as we can tell this looks like a permission issue of some kind. What's different about the illink tool is that it's probably the first external process in the build which doesn't run on .NET Framework and accesses the nuget catch in the systemprofile path.
The build itself runs on .NET Framework and the compiler as well. There are other external processes (like Razor and so on), but they don't seem to access the nuget cache paths as far as I can tell.

Another difference is that the MSBuild itself runs as a 32bit process, while the linker is a 64bit process. The path for the systemprofile is potentially different. The 32bit process will look into `C:\Windows\SysWOW64\config\systemprofile` (as seen by 64bit processes), while the 64bit process will look into `C:\Windows\System32\config\systemprofile` (the path is virtualized). It's possible that the MSBuild/NuGet which both run as 32bit wrote into the SysWOW64 path and the linker looks for it in System32.

Not sure what would "break it" suddenly - unless the CI system suddenly started to run under the SYSTEM account (while it didn't before), or the command line for the build changed (if the build was done with `dotnet build my.sln` it would run everything as 64bit I think).

**Comment by oliversalzburg** [comment]
I actually tried to build this project using the `dotnet` tool initially, but there seems to be some details that make it not work. There will be messages in the build output telling me to not use `dotnet`, but use `MSBuild` instead. So I came up with the current build approach.

But I had successful builds with the current approach for several weeks. The configuration of the CI runners has not changed in between, as far as I am aware. My assumption that seemed most plausible to me would be some kind of automated Windows update or .Net cleanup process having an impact on this. The machines the CI runners are deployed on are not domain-joined and should not be subject to any Windows policy application from our domain. They are also not joined into any system management solutions. The only things that I am aware of that could trigger on their own would be the Windows updates or default scheduled tasks.

This is to the best of my knowledge. If I can contribute anything else, let me know.

**Comment by vitek-karas** [comment]
I don't really have any ideas to be honest. The best I can think of is to somehow run some code (or if you can remote connect to the machine) to see if the file it fails on is really there and what are the ACLs on it. And maybe also check the x64/x86 mismatch mentioned above.

**Comment by oliversalzburg** [comment]
I can RDP into the machine. I will investigate those subjects and report back.
