### ISSUE TITLE
linker: NRE in `Mono.Linker.TypeMapInfo.MapOverrides`

### ISSUE THREAD

**Issue by radical** [dotnet/linker#2789]

**Comment by vitek-karas** [comment]
@radical does it repro still? The link to the failing build seems broken (I can't open that page, AzDo errors), but honestly looking around the code we would need a repro to diagnose this - it's really weird.

**Comment by radical** [comment]
Hit this again - [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1794263&view=logs&jobId=55f4943c-f76d-585b-7250-deab324f0a54&j=55f4943c-f76d-585b-7250-deab324f0a54&t=18a666a9-d033-504f-063f-baac7386b04a):
```
/_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReferenceConverter.cs(67,25): error IL1005: System.ComponentModel.ReferenceConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object): Error processing method 'System.ComponentModel.IContainer.Components.get' in assembly 'System.ComponentModel.Primitives.dll'. [D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Configuration.Json\tests\Microsoft.Extensions.Configuration.Json.Tests.csproj]
##[error]/_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReferenceConverter.cs(67,25): error IL1005: (NETCORE_ENGINEERING_TELEMETRY=Build) System.ComponentModel.ReferenceConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object): Error processing method 'System.ComponentModel.IContainer.Components.get' in assembly 'System.ComponentModel.Primitives.dll'.
  Mono.Linker.LinkerFatalErrorException: /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReferenceConverter.cs(67,25): error IL1005: System.ComponentModel.ReferenceConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object): Error processing method 'System.ComponentModel.IContainer.Components.get' in assembly 'System.ComponentModel.Primitives.dll'.
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.TypeMapInfo.MapOverrides(MethodDefinition method)
     at Mono.Linker.TypeMapInfo.MapVirtualMethods(TypeDefinition type)
     at Mono.Linker.TypeMapInfo.MapType(TypeDefinition type)
     at Mono.Linker.TypeMapInfo.EnsureProcessed(AssemblyDefinition assembly)
     at Mono.Linker.TypeMapInfo.GetBaseMethods(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.IsMethodNeededByTypeDueToPreservedScope(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.MarkMethodsIf(Collection`1 methods, Func`2 predicate, DependencyInfo& reason, MessageOrigin& origin)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger, Boolean throwOnFatalLinkerException)
```
