### ISSUE TITLE
DynamicallyAccessedMembersAnalyzer throws NotImplementedException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/linker#2847]
While compiling System.Formats.Tar, AD0001 is triggered due to an unhandled NotImplementedException:
```
Severity	Code	Description	Project	File	Line	Suppression State
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Microsoft.CodeAnalysis.Operations.ImplicitIndexerReferenceOperation'.
Exception occurred with following context:
Compilation: System.Formats.Tar
ISymbol: WriteChecksum (Method)

System.NotImplementedException: Microsoft.CodeAnalysis.Operations.ImplicitIndexerReferenceOperation
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitSimpleAssignment(ISimpleAssignmentOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitExpressionStatement(IExpressionStatementOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Formats.Tar (net7.0-windows)		1	Active
```

**Comment by stephentoub** [comment]
There are also more of these when compiling Corelib, e.g.
```
Severity	Code	Description	Project	File	Line	Suppression State
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'The method or operation is not implemented.'.
Exception occurred with following context:
Compilation: System.Private.CoreLib
ISymbol: EmptyTypes (Field)

System.NotImplementedException: The method or operation is not implemented.
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisAssignmentPattern.CollectDiagnostics()
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisPatternStore.<CollectDiagnostics>d__6.MoveNext()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Private.CoreLib		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Microsoft.CodeAnalysis.Operations.EventReferenceOperation'.
Exception occurred with following context:
Compilation: System.Private.CoreLib
ISymbol: add_EventSourceCreated (Method)

System.NotImplementedException: Microsoft.CodeAnalysis.Operations.EventReferenceOperation
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitSimpleAssignment(ISimpleAssignmentOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitExpressionStatement(IExpressionStatementOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Private.CoreLib		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Microsoft.CodeAnalysis.Operations.EventReferenceOperation'.
Exception occurred with following context:
Compilation: System.Private.CoreLib
ISymbol: remove_EventSourceCreated (Method)

System.NotImplementedException: Microsoft.CodeAnalysis.Operations.EventReferenceOperation
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitSimpleAssignment(ISimpleAssignmentOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitExpressionStatement(IExpressionStatementOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Private.CoreLib		1	Active
```

**Comment by stephentoub** [comment]
We can close this if you think it's already been addressed.  I'll re-open if it hasn't after we pick up a new linker.

**Comment by stephentoub** [comment]
@sbomer, using what's currently in dotnet/runtime, I still get these.  Is this expected still?
```
Severity	Code	Description	Project	File	Line	Suppression State
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Invalid'.
Exception occurred with following context:
Compilation: Microsoft.Extensions.Caching.Memory
ISymbol: GetCurrentStatistics (Method)

System.NotImplementedException: Invalid
   at ILLink.RoslynAnalyzer.DataFlow.CapturedReferenceValue..ctor(IOperation operation)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitFlowCapture(IFlowCaptureOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	Microsoft.Extensions.Caching.Memory (netstandard2.0)		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Invalid'.
Exception occurred with following context:
Compilation: System.Reflection.Metadata
ISymbol: GetRowCounts (Method)

System.NotImplementedException: Invalid
   at ILLink.RoslynAnalyzer.DataFlow.CapturedReferenceValue..ctor(IOperation operation)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitFlowCapture(IFlowCaptureOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Reflection.Metadata (net462)		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Invalid'.
Exception occurred with following context:
Compilation: System.Reflection.Metadata
ISymbol: GetRowCounts (Method)

System.NotImplementedException: Invalid
   at ILLink.RoslynAnalyzer.DataFlow.CapturedReferenceValue..ctor(IOperation operation)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitFlowCapture(IFlowCaptureOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Reflection.Metadata (net6.0)		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Invalid'.
Exception occurred with following context:
Compilation: System.Reflection.Metadata
ISymbol: GetRowCounts (Method)

System.NotImplementedException: Invalid
   at ILLink.RoslynAnalyzer.DataFlow.CapturedReferenceValue..ctor(IOperation operation)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitFlowCapture(IFlowCaptureOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	System.Reflection.Metadata (netstandard2.0)		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Invalid'.
Exception occurred with following context:
Compilation: Microsoft.Extensions.Caching.Memory
ISymbol: GetCurrentStatistics (Method)

System.NotImplementedException: Invalid
   at ILLink.RoslynAnalyzer.DataFlow.CapturedReferenceValue..ctor(IOperation operation)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitFlowCapture(IFlowCaptureOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	Microsoft.Extensions.Caching.Memory (net462)		1	Active
Message	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Invalid'.
Exception occurred with following context:
Compilation: Microsoft.Extensions.Caching.Memory
ISymbol: GetCurrentStatistics (Method)

System.NotImplementedException: Invalid
   at ILLink.RoslynAnalyzer.DataFlow.CapturedReferenceValue..ctor(IOperation operation)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitFlowCapture(IFlowCaptureOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimDataFlowAnalysis.ComputeTrimAnalysisPatterns()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__5_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	Microsoft.Extensions.Caching.Memory (net6.0)		1	Active
```

**Comment by stephentoub** [comment]
> would you be opposed to setting the AD0001 severity to warning in runtime to help us catch these on insertion?

My hesitancy is warnings fail the build and there's nothing a developer can do to address them short of disabling the rule (if any are non-deterministic).  We can try it once we're clean, though, and see how it goes.

**Comment by stephentoub** [comment]
> were you seeing these errors while working on some changes locally?

Nope, a clean main from a few hours ago.
