### ISSUE TITLE
UnreachableBlocksOptimizer hits NotSupportedException when compiling crossgen2 in runtime build

### ISSUE THREAD

**Issue by agocke** [dotnet/linker#2872]
Stack trace:

>Fatal error in IL Linker
  Unhandled exception. System.NotImplementedException: switch
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.IsConstantBranch(OpCode opCode, Int32 operand)
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.RemoveConditions()
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.RewriteBody()
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)

It looks like the problematic method might be ComputeDefaultOptions which looks like

```C#
 public static void ComputeDefaultOptions(out TargetOS os, out TargetArchitecture arch)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                os = TargetOS.Windows;
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                os = TargetOS.Linux;
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                os = TargetOS.OSX;
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.FreeBSD))
                os = TargetOS.FreeBSD;
            else
                throw new NotImplementedException();

            switch (RuntimeInformation.ProcessArchitecture)
            {
                case Architecture.X86:
                    arch = TargetArchitecture.X86;
                    break;
                case Architecture.X64:
                    arch = TargetArchitecture.X64;
                    break;
                case Architecture.Arm:
                    arch = TargetArchitecture.ARM;
                    break;
                case Architecture.Arm64:
                    arch = TargetArchitecture.ARM64;
                    break;
                default:
                    Console.WriteLine((int)RuntimeInformation.ProcessArchitecture);
                    throw new NotImplementedException();
            }

        }
```

**Comment by agocke** [comment]
To replicate, commit is https://github.com/agocke/runtime/commit/e564c27a982679a15783fc8707e5bdf9023ae6d1, then `./build.sh clr+libs+packs.product`, on Mac (which is where trimming happens by default, this could be enabled on other platforms with some modifications to the crossgen2 project file)

**Comment by agocke** [comment]
@marek-safar Any ideas here?

**Comment by vitek-karas** [comment]
Added a test which reproes this in https://github.com/dotnet/linker/pull/2887

Note about the repro:
There's a bug in linker where if the first thing method does is a switch the const. prop code will not recognize it as optimizable branch instruction. So the test adds a dummy call before it. We might as well fix it:
https://github.com/dotnet/linker/blob/4c95f11f5c566c1090beae99fe7c5668aa4b7952/src/linker/Linker.Steps/UnreachableBlocksOptimizer.cs#L895
Should be `i >= 3`.

**Comment by vitek-karas** [comment]
The bug is essentially the fact that the const. prop doesn't have code to optimize `switch` instructions. It recognizes them as branch instructions, so it tries to optimize them, but when it actually works on it, it doesn't know what to do.

Note that this is only hittable in Release built input, in Debug builds Roslyn produces a pattern around switch which linker doesn't recognize currently.

**Comment by vitek-karas** [comment]
Workaround would be to simply skip over `switch` instruction - don't support optimizing them for now.

Actually optimizing `switch` instructions is obviously doable, but requires much more work. Some of the patterns which hit this would benefit from such support though (the one above doesn't really, but there are others hit in runtime repo).

**Comment by vitek-karas** [comment]
https://github.com/dotnet/linker/pull/2889 has a "fix" - basically intentionally disable any support for switch instruction block removal to avoid the exception.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/linker/pull/2889 should fix this issue - that is should make the linker NOT crash.
