### ISSUE TITLE
ILLink : error IL1012 with macOS, .NET 7.0

### ISSUE THREAD

**Issue by nilaoda** [dotnet/linker#3157]
```
  Optimizing assemblies for size. This process might take a while.
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues [/Users/runner/work/N_m3u8DL-RE/N_m3u8DL-RE/src/N_m3u8DL-RE/N_m3u8DL-RE.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'target')
     at Mono.Cecil.Cil.ILProcessor.InsertAfter(Instruction target, Instruction instruction)
     at Mono.Linker.LinkerILProcessor.InsertAfter(Instruction target, Instruction instruction)
     at Mono.Linker.Steps.MarkStep.ProcessPendingTypeChecks()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```
Detail here:  
https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/3663371272/jobs/6193112246

**Comment by vitek-karas** [comment]
This was fixed by https://github.com/dotnet/linker/pull/3088 but that fix is only available in .NET 8.0 SDK.
Unfortunately the fix is rather large so it raises the risk of taking the fix for servicing. I'll look into it.

In theory there might be a workaround as the bug is order dependent - if the trimmer sees the code in different order it might work, but it's really hard to guess which order will work and which won't.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/linker/pull/3161 is the 7.0 port of the fix.

**Comment by vitek-karas** [comment]
Note that this issue is only the trimmer, it doesn't apply to NativeAOT (which also does triming), so if you manage to get your app working in NativeAOT, this issue should not impact that.
